### ISSUE TITLE
Program starts and then closes when loading a DNG folder

### ISSUE THREAD

**Issue by NickMDal** [octopuscinema/raw-player#24]
Windows 10.  Video is ProRes RAW converted with Raw Converter.  Source is Z Cam to Ninja V+.

Win10 Home 10.0.19045 Build 19045

The program immediately closes when a folder with DNG is loaded.  Running the single file executable as admin does not change this.

**Comment by octopus-russell** [comment]
Hi, sorry for the delay is responding. Does this happen with all DNG sequences, or just some/specific DNG sequences? Would you be able to share a small amount of frames of the DNG sequence in question?

**Comment by cfmayer** [comment]
I have the same problem on v1.1.1. Drop in the folder and the program quits. I can provide a short clip for you to test on, but I'd rather not post a public URL. The footage was recorded on a Ninja V+ from a Canon R5 in Prores Raw and converted to CDNG using the Raw Converter app on Windows.

**Comment by octopus-russell** [comment]
Hi @cfmayer, thanks for the information. You can send/share the footage URL to russellnewman@octopuscinema.com

**Comment by cfmayer** [comment]
Email sent. I also forgot to mention this is 8k footage.

**Comment by octopus-russell** [comment]
Thanks for sharing the footage. It seems the jpeg compression used in those DNGs doesn't conform to the Adobe DNG jpeg spec - they don't load in Adobe software. It might be worth submitting a ticket to the developers of the Raw Converter app - they should be generating DNGs which conform to the spec. I can see they work in DaVinci Resolve though. If we can figure out what DaVinci Resolve does to load them, we could probably also load them. For now we will handle the issue a bit more gracefully i.e. error message instead of crash. A workaround could be either exporting uncompressed and/or you could try using slimRAW to recompress them.

**Comment by NickMDal** [comment]
Hi.  Here is 6 frames of footage from the OP.  It was converted from ProRes RAW by RawConverter.  That app is one of two that allows RAW footage to be imported into Davinci Resolve.  So there are lots of potential users.

[NINJVP_S001_S001_T002.zip](https://github.com/octopuscinema/raw-player/files/15046412/NINJVP_S001_S001_T002.zip)

**Comment by octopus-russell** [comment]
We've implemented lossy DNG decoding now which includes support for Cinema DNG exported from the RawConverter application. Will be in the next release coming in the next week.

**Comment by octopus-russell** [comment]
Lossy DNG support for SlimRAW and RawConverter is now in the 2.1.0 release
